name: General Feature Request
description: Suggest a feature affecting infrastructure, DevOps, docs, or other cross-cutting concerns
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Use this template for infrastructure, DevOps, documentation, or cross-cutting features.
        For **data models/DTOs**, use the **Data Model Addition** template instead.
        For **Discord Bot** or **Web App** features, use the appropriate template.
        See [agents.md — Cross-Cutting Guidelines](https://github.com/nbely/pokesandbox/tree/master/.github/agents.md#cross-cutting-guidelines) for project conventions.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature or enhancement would you like to see?
      placeholder: |
        Describe the feature or enhancement you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        Is your feature request related to a problem? Describe the problem or use case.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which part of the project does this affect?
      options:
        - Shared Library — Cache
        - DevOps/CI-CD
        - Documentation
        - Testing/DX
        - Other
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How would you like this to be implemented?
      placeholder: |
        Describe your proposed solution or implementation approach.
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How do we verify this feature is complete? List specific, testable conditions.
      placeholder: |
        - [ ] Change is implemented and tested
        - [ ] Documentation is updated if applicable
        - [ ] No regressions in existing functionality
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope & Boundaries
      description: What is explicitly in and out of scope?
      placeholder: |
        In scope:
        - Model, DTO, and zod schemas in /shared
        - Index re-exports

        Out of scope:
        - tRPC router (webapp issue)
        - Bot slash command (bot issue)
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - 'Low'
        - 'Medium'
        - 'High'
        - 'Critical'
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any additional information or examples?
      placeholder: Add any other relevant information.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this request hasn't been made
          required: true
        - label: I have described acceptance criteria
          required: true
